name: Counter-Craft
main: Counter_Craft.Main
author: Wolf_2789
version: 0.1
commands:
  cc:
    description: Counter-Craft Admin.
  h:
    description: Informations about commands.
  b:
    description: Allows to buy weapons and ammo.
  e:
    description: Allows to buy enchantments.
  